AWSTemplateFormatVersion: 2010-09-09
Description:
  Create S3 Endpoint

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Project Name
        Parameters:
          - ProjectName

Parameters:
  ProjectName:
    Type: String

Resources:
  VPCS3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - Fn::ImportValue: !Sub '${ProjectName}-private-route-a'
        - Fn::ImportValue: !Sub '${ProjectName}-private-route-c'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId:
        Fn::ImportValue: !Sub '${ProjectName}-vpc'

Outputs:
  VPCS3Endpoint:
    Value: !Ref VPCS3Endpoint
    Export:
      Name: !Sub '${ProjectName}-vpc-s3-endpoint'
