AWSTemplateFormatVersion: 2010-09-09
Description:
  Create S3 Endpoint

#---------------------------------------------------------------------------
Metadata:
#---------------------------------------------------------------------------
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Parameters:
          - SystemName
          - Env

#---------------------------------------------------------------------------
Parameters:
#---------------------------------------------------------------------------
  SystemName:
    Description: System identifier
    Type: String
    MinLength: 1
    Default: example
  Env:
    Description: Environment name. e.g. prod, stg, dev
    Type: String
    MinLength: 1
    Default: prod

#---------------------------------------------------------------------------
Resources:
#---------------------------------------------------------------------------

  #---------------------------------------------------------------------------
  VPCS3Endpoint:
  #---------------------------------------------------------------------------
    Type: AWS::EC2::VPCEndpoint
    Properties:
      RouteTableIds:
        - Fn::ImportValue: !Sub '${SystemName}-${Env}-application-rtb-1'
        - Fn::ImportValue: !Sub '${SystemName}-${Env}-application-rtb-2'
        - Fn::ImportValue: !Sub '${SystemName}-${Env}-application-rtb-3'
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcId:
        Fn::ImportValue: !Sub '${SystemName}-${Env}-vpc'
      # tags not yet supported
      # https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/196
      # Tags:
        # - Key: Name
          # Value: !Sub ${SystemName}-${Env}-vpc-endpoint
        # - Key: SystemName
          # Value: !Sub ${SystemName}
        # - Key: Env
          # Value: !Sub ${Env}

#---------------------------------------------------------------------------
Outputs:
#---------------------------------------------------------------------------
  VPCS3Endpoint:
    Value: !Ref VPCS3Endpoint
    Export:
      Name: !Sub '${SystemName}-${Env}-vpc-s3-endpoint'
